version: "3"
services:

  db:
    image: mysql:5.6.32
    container_name: requeldb
    ports:
      - "3306:3306"
    networks:
      - requel-net
    environment:
      - "MYSQL_ROOT_PASSWORD=pa33w0rd"

  web:
    depends_on:
      - db
    image: rreganjr/requel:1.0.2
    ports:
      - "8080:8080"
    networks:
      - requel-net
    environment:
      - "_JAVA_OPTIONS=-Xms1g -Xmx1g -XX:MaxMetaspaceSize=512m -XX:+UseConcMarkSweepGC -XX:+CMSParallelRemarkEnabled"
      - "SPRING_DATASOURCE_URL=jdbc:mysql://requeldb:3306/requeldb?createDatabaseIfNotExist=true"
      - "SPRING_DATASOURCE_USERNAME=root"
      - "SPRING_DATASOURCE_PASSWORD=pa33w0rd"

networks:
  requel-net:
    driver: bridge

