services:
  db:
    image: mysql:8.4
    ports:
      - "3307:3306"
    networks:
      - requel-net
    environment:
      - "MYSQL_ROOT_PASSWORD=pa33w0rd"
      - "MYSQL_DATABASE=requel"
      - "MYSQL_ROOT_HOST=%"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p\"$MYSQL_ROOT_PASSWORD\" --silent"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
    restart: unless-stopped

  web:
    depends_on:
      db:
        condition: service_healthy
    image: rreganjr/requel:1.1.0
    ports:
      - "8080:8080"
    networks:
      - requel-net
    environment:
      - "_JAVA_OPTIONS=-Xms2g -Xmx2g -XX:MaxMetaspaceSize=512m -XX:+UseG1GC"
      - "SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/requel?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC"
      - "SPRING_DATASOURCE_USERNAME=root"
      - "SPRING_DATASOURCE_PASSWORD=pa33w0rd"
    restart: unless-stopped

networks:
  requel-net:
    driver: bridge
