#!/usr/bin/env bash
# Generate doc/work/<release>/INDEX.md and the index block in doc/README.md.
#
# Issue state is NEVER stored in the files -- the issue is the source of truth and this
# script reads it fresh. One `gh issue list` call covers the whole release; do not add a
# per-issue lookup (see the GraphQL budget note in CLAUDE.md).
#
#   ./scripts/gen-doc-index.sh          # release from the root pom
#   ./scripts/gen-doc-index.sh 2.1      # explicit
set -euo pipefail
root="$(git rev-parse --show-toplevel)"; cd "$root"
REPO="${REPO:-rreganjr/Requel}"

RELEASE="${1:-$(sed '/<parent>/,/<\/parent>/d' pom.xml \
  | sed -n 's:.*<version>\([0-9][0-9]*\.[0-9][0-9]*\)\..*</version>.*:\1:p' | head -1)}"
[ -n "$RELEASE" ] || { echo "!! could not derive release from pom.xml; pass one" >&2; exit 1; }

dir="doc/work/$RELEASE"
[ -d "$dir" ] || { echo "!! $dir does not exist" >&2; exit 1; }

state="$(mktemp)"; trap 'rm -f "$state"' EXIT
echo ">> fetching issue state for $REPO ..." >&2
gh issue list --repo "$REPO" --state all --limit 1000 \
  --json number,title,state --jq '.[] | "\(.number)\t\(.state)\t\(.title)"' > "$state"

python3 - "$dir" "$RELEASE" "$state" <<'PY'
import os, re, sys, collections
dir_, release, statefile = sys.argv[1], sys.argv[2], sys.argv[3]

issues = {}
for line in open(statefile):
    n, st, title = line.rstrip('\n').split('\t', 2)
    issues[int(n)] = (st, title)

by_issue, unattributed = collections.defaultdict(list), []
for f in sorted(os.listdir(dir_)):
    if not f.endswith('.md') or f == 'INDEX.md':
        continue
    m = re.match(r'^(\d+)[-_]', f)
    # A leading number is only an issue number if it resolves to a real issue.
    # doc/work/2.0/20-release-plan.md is the *2.0* release plan, not issue #20.
    if m and int(m.group(1)) in issues:
        by_issue[int(m.group(1))].append(f)
    else:
        unattributed.append(f)

out = [f'# Release {release} — work artifacts', '',
       'Generated by `scripts/gen-doc-index.sh`. Do not edit by hand.', '',
       'Issue state is read live from GitHub at generation time; it is not stored in the files.', '',
       '| Issue | State | Title | Artifacts |', '|---|---|---|---|']

for n in sorted(by_issue):
    st, title = issues[n]
    files = ', '.join(f'[{f}]({f})' for f in sorted(by_issue[n]))
    badge = {'CLOSED': 'closed', 'OPEN': '**open**'}.get(st, st)
    out += [f'| [#{n}](https://github.com/rreganjr/Requel/issues/{n}) | {badge} | {title} | {files} |']

if unattributed:
    out += ['', '## Unattributed', '',
            'No issue number in the filename, or a leading number that is not an issue '
            '(e.g. `20-release-plan.md` is the 2.0 release plan). Informational, not a defect.', '']
    out += [f'- [{f}]({f})' for f in sorted(unattributed)]

out += ['', f'{len(by_issue)} issues, '
            f'{sum(len(v) for v in by_issue.values()) + len(unattributed)} files.']

open(os.path.join(dir_, 'INDEX.md'), 'w').write('\n'.join(out) + '\n')
print(f'>> wrote {dir_}/INDEX.md — {len(by_issue)} issues, {len(unattributed)} unattributed',
      file=sys.stderr)

# --- the block inside doc/README.md: one line per release folder -------------
rows = []
for d in sorted(os.listdir('doc/work'), reverse=True):
    p = os.path.join('doc/work', d)
    if not os.path.isdir(p):
        continue
    n = len([x for x in os.listdir(p) if x.endswith('.md') and x != 'INDEX.md'])
    label = 'proposals, not yet scheduled' if d == 'backlog' else f'release {d}'
    link = f'[{d}](work/{d}/INDEX.md)' if d != 'backlog' else f'[{d}](work/{d}/)'
    rows.append(f'| {link} | {label} | {n} |')

readme = open('doc/README.md').read()
block = '\n'.join(['<!-- BEGIN INDEX -->', '', '| Folder | Contents | Files |', '|---|---|---|',
                   *rows, '', '<!-- END INDEX -->'])
readme = re.sub(r'<!-- BEGIN INDEX -->.*?<!-- END INDEX -->', block, readme, flags=re.S)
open('doc/README.md', 'w').write(readme)
print('>> refreshed the index block in doc/README.md', file=sys.stderr)
PY

# Links are checked after the index is written, so the generated INDEX.md and the
# README block are covered too. The checker needs no gh and no network; it is runnable
# on its own (scripts/check-doc-links.sh) and its exit code is the exit code here.
"$root/scripts/check-doc-links.sh"
