/*
 * $Id: NLPNavigatorTreeNodeFactory.java,v 1.2 2008/12/17 02:00:42 rregan Exp $
 * Copyright (c) 2008 Ron Regan Jr. All Rights Reserved.
 */
package edu.harvard.fas.rregan.nlp.ui;

import nextapp.echo2.app.Label;
import nextapp.echo2.app.event.ActionEvent;

import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

import echopointng.tree.MutableTreeNode;
import edu.harvard.fas.rregan.uiframework.navigation.WorkflowDisposition;
import edu.harvard.fas.rregan.uiframework.navigation.event.EventDispatcher;
import edu.harvard.fas.rregan.uiframework.navigation.event.NavigationEvent;
import edu.harvard.fas.rregan.uiframework.navigation.event.OpenPanelEvent;
import edu.harvard.fas.rregan.uiframework.navigation.event.UpdateEntityEvent;
import edu.harvard.fas.rregan.uiframework.navigation.tree.AbstractNavigatorTreeNodeFactory;
import edu.harvard.fas.rregan.uiframework.navigation.tree.NavigatorTree;
import edu.harvard.fas.rregan.uiframework.navigation.tree.NavigatorTreeNode;
import edu.harvard.fas.rregan.uiframework.navigation.tree.NavigatorTreeNodeUpdateListener;
import edu.harvard.fas.rregan.uiframework.panel.PanelActionType;

/**
 * @author ron
 */
@Component("nlpNavigatorTreeNodeFactory")
@Scope("singleton")
public class NLPNavigatorTreeNodeFactory extends AbstractNavigatorTreeNodeFactory {

	/**
	 * The property name to use to control the label on the parser node
	 * generated by the factory.
	 */
	public final static String PROP_PARSER_NODE_LABEL = "ParserNodeLabel";

	/**
	 * @param eventDispatcher
	 */
	public NLPNavigatorTreeNodeFactory() {
		super(NLPNavigatorTreeNodeFactory.class.getName(), NLPNavigatorPanel.class);
	}

	/**
	 * @see edu.harvard.fas.rregan.uiframework.navigation.tree.NavigatorTreeNodeFactory#createTreeNode(edu.harvard.fas.rregan.uiframework.navigation.tree.NavigatorTree,
	 *      java.lang.Object)
	 */
	public MutableTreeNode createTreeNode(EventDispatcher eventDispatcher, NavigatorTree tree,
			Object object) {

		NavigationEvent openParserPanelEvent = new OpenPanelEvent(tree, PanelActionType.Editor,
				null, null, NLPPanelNames.PARSER_PANEL_NAME, WorkflowDisposition.NewFlow);

		String sparserPanelNodeLabel = getResourceBundleHelper(tree.getLocale()).getString(
				PROP_PARSER_NODE_LABEL, "Parser");

		NavigatorTreeNode parserPanelTreeNode = new NavigatorTreeNode(eventDispatcher, null,
				new Label(sparserPanelNodeLabel), openParserPanelEvent);

		return parserPanelTreeNode;
	}

	private static class UpdateListener implements NavigatorTreeNodeUpdateListener {
		static final long serialVersionUID = 0L;

		private final NavigatorTreeNode projectTreeNode;

		private UpdateListener(NavigatorTreeNode projectTreeNode) {
			this.projectTreeNode = projectTreeNode;
		}

		@Override
		public void actionPerformed(ActionEvent e) {
			if (e instanceof UpdateEntityEvent) {
			}
		}
	}
}
