<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.rreganjr.requel</groupId>
        <artifactId>Requel-parent</artifactId>
        <version>1.2.0</version>
        <relativePath>../../pom.xml</relativePath>
    </parent>
    <artifactId>user-ui</artifactId>
    <packaging>jar</packaging>

    <dependencies>
        <dependency>
            <groupId>com.rreganjr.requel</groupId>
            <artifactId>ui-core</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.rreganjr.requel</groupId>
            <artifactId>user-domain</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.rreganjr.requel</groupId>
            <artifactId>user-jpa</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.rreganjr.requel</groupId>
            <artifactId>platform-identity</artifactId>
            <version>${project.version}</version>
        </dependency>
    </dependencies>
</project>
